sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: antarcticle_<%= Rails.env %>

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "sqlite" %>

development:
  <<: *defaults

test:
  <<: *defaults

<%
require File.expand_path("../lib/jndi_properties", __FILE__)
%>
production:
  adapter: mysql
  username: <%= JndiProperties['ANTARCTICLE_DB_USER'] || 'root' %>
  password: <%= JndiProperties['ANTARCTICLE_DB_PASSWORD'] || '' %>
  url:      <%= JndiProperties['ANTARCTICLE_DB_URL']      || 'jdbc:mysql://localhost:3306/antarcticle' %>


